#!/usr/bin/make -f

# sudo apt install pkg-config cython3 libpython3-dev

CROSS ?= 
ARCH_CFLAGS ?= 

ARCH_ID := $(shell '$(TRGT)gcc' -dumpmachine)

# See: https://peps.python.org/pep-3149/
PYMOD_SOABI := $(shell python3 -c "import sysconfig; print(sysconfig.get_config_var('SOABI'));")
PYMOD_SUFFIX := $(shell python3 -c "import sysconfig; print(sysconfig.get_config_var('EXT_SUFFIX'));")

OBJ_DIR=obj-$(ARCH_ID)
PROGRAM=picsim-$(ARCH_ID)
PYMODULE=picsim$(PYMOD_SUFFIX)

CC= $(CROSS)gcc
CXX= $(CROSS)g++
STRIP= $(CROSS)strip

PYTHON= python3
CYTHON= cython3

RM= rm --force --verbose

PKGCONFIG= pkg-config
PACKAGES= python3-embed

ifndef PACKAGES
PKG_CONFIG_CFLAGS=
PKG_CONFIG_LDFLAGS=
PKG_CONFIG_LIBS=
else
PKG_CONFIG_CFLAGS=`pkg-config --cflags $(PACKAGES)`
PKG_CONFIG_LDFLAGS=`pkg-config --libs-only-L $(PACKAGES)`
PKG_CONFIG_LIBS=`pkg-config --libs-only-l $(PACKAGES)`
endif

CFLAGS= \
	-Wall \
	-fwrapv \
	-fstack-protector-strong \
	-Wall \
	-Wformat \
	-Werror=format-security \
	-Wdate-time \
	-D_FORTIFY_SOURCE=2 \
	-fPIC

LDFLAGS= \
	-Wl,-O1 \
	-Wl,-Bsymbolic-functions \
	-Wl,-z,relro \
	-Wl,--as-needed \
	-Wl,--no-undefined \
	-Wl,--no-allow-shlib-undefined \
	-Wl,-Bsymbolic-functions \
	-Wl,--dynamic-list-cpp-new \
	-Wl,--dynamic-list-cpp-typeinfo

CYFLAGS= \
	-3 \
	--cplus \
	-X language_level=3 \
	-X boundscheck=False

CSTD=-std=gnu17
CPPSTD=-std=gnu++17

OPTS= -O2 -g

DEFS= \
	-DDEBUG

INCS= \
	-I. -I../include

CYINCS= \
	-I.

LIBS= \

all: $(PYMODULE)

OBJS= \
	$(OBJ_DIR)/common.o \
	$(OBJ_DIR)/p16fxxx.o \
	$(OBJ_DIR)/p16fxxxe.o \
	$(OBJ_DIR)/p18fxxx.o \
	$(OBJ_DIR)/hexfile.o \
	$(OBJ_DIR)/periferic16.o \
	$(OBJ_DIR)/periferic16e.o \
	$(OBJ_DIR)/periferic18.o \
	$(OBJ_DIR)/icsp.o \
	$(OBJ_DIR)/icsp18.o \
	$(OBJ_DIR)/util.o \
	$(OBJ_DIR)/common/serial.o \
	$(OBJ_DIR)/common/bitbang_uart.o

OBJS+= $(patsubst ../src/p16/%.c,$(OBJ_DIR)/p16/%.o,$(wildcard ../src/p16/*.c)) 
OBJS+= $(patsubst ../src/p16e/%.c,$(OBJ_DIR)/p16e/%.o,$(wildcard ../src/p16e/*.c)) 
OBJS+= $(patsubst ../src/p18/%.c,$(OBJ_DIR)/p18/%.o,$(wildcard ../src/p18/*.c)) 
OBJS+= $(patsubst ../src/pics/%.c,$(OBJ_DIR)/pics/%.o,$(wildcard ../src/pics/*.c)) 

PYX_SRCS= \
	picsim.pyx

picsim.h picsim.cpp : picsim.pyx cpicsim.pxd

PYX_CPPS= $(addprefix $(OBJ_DIR)/,$(subst .pyx,.cpp,$(PYX_SRCS)))
PYX_OBJS= $(addprefix $(OBJ_DIR)/,$(subst .pyx,.o,$(PYX_SRCS)))

$(PROGRAM): $(OBJS) $(OBJ_DIR)/main.o
	$(CXX) $(CPPSTD) $(CSTD) $(LDFLAGS) $(PKG_CONFIG_LDFLAGS) -o $@ $+ $(LIBS) $(PKG_CONFIG_LIBS)

$(PYMODULE): $(OBJS) $(PYX_OBJS)
	$(CXX) -shared $(CPPSTD) $(CSTD) $(LDFLAGS) $(PKG_CONFIG_LDFLAGS) -o $@ $+ $(LIBS) $(PKG_CONFIG_LIBS)

$(OBJ_DIR)/%.o: %.cpp
	@mkdir -p '$(shell dirname "$@")'
	$(CXX) $(CPPSTD) $(OPTS) -o $@ -c $< $(DEFS) $(INCS) $(CFLAGS) $(ARCH_CFLAGS) $(PKG_CONFIG_CFLAGS)

$(OBJ_DIR)/%.o: %.c
	@mkdir -p '$(shell dirname "$@")'
	$(CC) $(CSTD) $(OPTS) -o $@ -c $< $(DEFS) $(INCS) $(CFLAGS) $(ARCH_CFLAGS) $(PKG_CONFIG_CFLAGS)

$(OBJ_DIR)/%.o: ../src/%.cpp
	@mkdir -p '$(shell dirname "$@")'
	$(CXX) $(CPPSTD) $(OPTS) -o $@ -c $< $(DEFS) $(INCS) $(CFLAGS) $(ARCH_CFLAGS) $(PKG_CONFIG_CFLAGS)

$(OBJ_DIR)/%.o: ../src/%.c
	@mkdir -p '$(shell dirname "$@")'
	$(CC) $(CSTD) $(OPTS) -o $@ -c $< $(DEFS) $(INCS) $(CFLAGS) $(ARCH_CFLAGS) $(PKG_CONFIG_CFLAGS)

%.cpp: %.pyx
	@mkdir -p '$(shell dirname "$@")'
	$(CYTHON) $(CYFLAGS) $(CYINCS) -o $@ $<

info:
	@echo PYX_NAMES: $(PYX_NAMES)
	@echo PYX_SRCS:  $(PYX_SRCS)
	@echo PYX_OBJS:  $(PYX_OBJS)
	@echo OBJS:      $(OBJS)

clean:
	$(RM) $(OBJS) $(PYX_OBJS) $(PYX_CPPS) $(PROGRAM) $(PYMODULE)
	$(RM) $(subst .pyx,.cpp,$(PYX_SRCS))
	$(RM) $(subst .pyx,_api.cpp,$(PYX_SRCS))
	$(RM) $(subst .pyx,.h,$(PYX_SRCS))
	$(RM) $(subst .pyx,_api.h,$(PYX_SRCS))

cleanall: clean
	@find . -name '*.o' -exec $(RM) {} +
	@find . -name '*.a' -exec $(RM) {} +
	@find . -name '*.so' -exec $(RM) {} +
	@find . -name '*.pyc' -exec $(RM) {} +
	@find . -name '*.pyo' -exec $(RM) {} +
	@find . -name '*.bak' -exec $(RM) {} +
	@find . -name '*~' -exec $(RM) {} +
	@rmdir -v *obj 2>/dev/null 1>/dev/null || true
	@$(RM) core

.PHONY: all clean info
